version: '3.8'
services:
  workload_mgmt_db:
    container_name: workload_mgmt_db
    image: mysql:8.4.0
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
